#简答题

####一.
    `js是一门脚本语言, js执行引擎单独分配一个固定的线程去执行js代码。
        js可以通过promise、定时器等js api等添加异步任务到js引擎提供的两个任务队列中，promise任务队列
      优先级高， 定时器任务队列优先级低，前一个队列称为是微任务队列，
       后一个队列称为是宏任务队列。 宏任务有:IO(鼠标、键盘事件、网络请求
       产生结果)、定时器、requestAnimationFrame、setImmediate；微任务有、promise、
      nextTick、MutationObserver。只有产生结果任务才会被添加到任务队列中。添加任务到任务队列中当然是另一些线程做的，
        比如定时器线程、io线程等。js执行线程类似于永不停歇地转圈圈，js文件第一次加载时js执行线程把所有同步代码执行完， 然后检查微任务队列是否
      有任务要执行， 如果有，js执行线程会一个接一个的从微任务队列取任务执行、知道微任务队列为空为止，然后去检查宏任务队列是否有任务要执行，
      如果有那取一个宏任务执行，执行完了再去执行微任务知道微任务队列为空再去执行一个宏任务。如此周而复始循环， 就是js执行线程的事件循环。
      也就是除了js文件第一次加载时js线程是直接执行js代码， 后面就一直在微任务和宏任务之间切换。
`

#代码题
####一.
```javascript
async function generate(value){
  return await new Promise(resolve => { setTimeout(() => resolve(value), 10); });
}```

```javascript
async function execute() {
  const a = await generate('hello');
  const b = await generate('lagou');
  await a = 'i love u';
  console.log(a + b + c);
}```
####二.
#####1.
```javascript
let isLastInStock = function(cars) {
  const f = fp.flowRight(fp.prop('in_stock'), fp.last)
  return f(cars);
}```
#####2.
```javascript
let isFirstInStock = function(cars) {
    const f = fp.flowRight(fp.prop('name'), fp.first)
    return f(cars);
  }
```
#####3
```javascript
let averageDollarValue = function(cars) {
   const f = fp.flowRight(_average, fp.map(function(car){return car.dollar_value;}))
   return f(cars)
 }```
#####4
```javascript
let sanitizeNames = function(names) {
   const f = fp.flowRight(fp.map(_underscore), fp.map(fp.lowerCase));
   return f(names);
 }
```
####三
#####1
```javascript
let ex1 = num => maybe.map(fp.map(v => fp.add(v, num)));```

#####2
```javascript
let ex2 = num => xs.map(fp.first);```
#####3
```javascript
let ex3 = safeProp('name')(user).map(fp.first);```
#####4
```javascript
let ex4 = n => Maybe.of(n).map(parseInt)```
####四
```javascript
class MyPromise {
   static PENDING = 'pending';
   static FULFILLED = 'fulFilled';
   static REJECTED = 'rejected';
   constructor(executor) {
     try {
       executor(this.resolve, this.reject);
     } catch (e) {
       this.reject(e);
     }
   }
   status = MyPromise.PENDING;
   value = undefined;
   reason = undefined;
   resolve = value => {
     if (this.status !== MyPromise.PENDING) return;
     this.status = MyPromise.FULFILLED;
     this.value = value;
     while (this.successCallBack.length) this.successCallBack.shift()();
   };
   reject = reason => {
     if (this.status !== MyPromise.PENDING) return;
     this.status = MyPromise.REJECTED;
     this.reason = reason;
     while (this.failCallBack.length) this.failCallBack.shift()();
   };
   successCallBack = [];
   failCallBack = [];
   then = (successCallBack, failCallBack) => {
     successCallBack = successCallBack ? successCallBack : value => value;
     failCallBack = failCallBack
       ? failCallBack
       : reason => {
           throw reason;
         };
     let promise2 = new Promise((resolve, reject) => {
       if (this.status === MyPromise.FULFILLED) {
         setTimeout(() => {
           try {
             let x = successCallBack(this.value);
             MyPromise.resolvePromise(promise2, x, resolve, reject);
           } catch (e) {
             reject(e);
           }
         }, 0);
       } else if (this.status === MyPromise.REJECTED) {
         setTimeout(() => {
           try {
             let x = failCallBack(this.reason);
             MyPromise.resolvePromise(promise2, x, resolve, reject);
           } catch (e) {
             reject(e);
           }
         }, 0);
       } else {
         if (successCallBack) {
           this.successCallBack.push(() => {
             setTimeout(() => {
               try {
                 let x = successCallBack(this.value);
                 MyPromise.resolvePromise(promise2, x, resolve, reject);
               } catch (e) {
                 reject(e);
               }
             }, 0);
           });
         }
         if (failCallBack) {
           this.failCallBack.push(() => {
             setTimeout(() => {
               try {
                 let x = failCallBack(this.reason);
                 MyPromise.resolvePromise(promise2, x, resolve, reject);
               } catch (e) {
                 reject(e);
               }
             }, 0);
           });
         }
       }
     });
     return promise2;
   };
   static resolvePromise = (promise2, x, resolve, reject) => {
     if (promise2 === x) {
       return reject(
         new TypeError('Chaining cycle detected for promise #/<Promise/>'),
       );
     }
     if (x instanceof MyPromise) {
       x.then(resolve, reject);
     } else resolve(x);
   };
   static all(array) {
     const result = [];
     return new MyPromise((resolve, reject) => {
       let index = 0;
       function addData(key, value) {
         result[key] = value;
         index += 1;
         if (index === array.length) {
           resolve(result);
         }
       }
       for (let i = 0; i < array.length; i++) {
         const current = array[i];
         if (current instanceof MyPromise) {
           current.then(value => addData(i, value), reject);
         } else {
           addData(i, current);
         }
       }
     });
   }
   static resolve(value) {
     if (value instanceof MyPromise) return value;
     return new MyPromise(resolve => resolve(value));
   }
   finally = callback => {
     return this.then(
       value => {
         return MyPromise.resolve(callback()).then(() => value);
       },
       reason => {
         return MyPromise.resolve(callback()).then(() => {
           throw reason;
         });
       },
     );
   };
   catch = failCallback => {
     return this.then(undefined, failCallback);
   };
 }    

```
   
